### ISSUE TITLE
Setup did not install some directories

### ISSUE THREAD

**Issue by bgouhier** [Jomiri/pyfiberamp#1]
After running setup.py the following directories are missing in site-packages:
pyfiberamp/utils
pyfiberamp/spectroscopies
fiber_spectra

copying them manually from git repo solved the issue

**Comment by Jomiri** [comment]
Hi,
thanks for the heads-up and even bigger thanks for interest in my project! Setup.py should be working now. I really should have uploaded the project to PyPI ages ago to make the installation more convenient, but I have been working hard on the next feature: time-dynamic simulations. Stay tuned! I am also glad to answer any further questions.

**Comment by bgouhier** [comment]
No worries ! Great project, gives me similar results to RP =)  I planned to do the same thing for a couple of years now but never got enough motivation !

I'll keep an eye on it =)

**Comment by Jomiri** [comment]
Thank you for the kind words!
