### ISSUE TITLE
Uninitialized arrays causing occasional test failures

### ISSUE THREAD

**Issue by u55** [Jomiri/pyfiberamp#5]
Hi. I was experiencing intermittent test failures in  `test_dynamic_simulation.py` with the simulation result sometimes being populated with NaN's. Replacing `np.empty_like` with `np.zeros_like` for the creation of `P_hat_forward` and `P_hat_backward` in `dynamic/dynamic_solver_python.py` seems to fix the problem for me. Thanks.

**Comment by Jomiri** [comment]
Thanks for the notice! Initializing the arrays with zeroes as you suggested is a better practice anyway so I made the change. I haven't encountered this issue myself, though, but it could be platform-dependent.
